sudo: false
dist: trusty
language: csharp
mono: none
dotnet: 2.0.0
solution: Com.DanLiris.Service.Sales.sln
services:
    - docker
env:
    - ASPNETCORE_ENVIRONMENT=Test

before_install:
    - bash Dockerfile.test.build.sh
    
install: true

before_script:
    - docker-compose -f docker-compose.test.yml up -d
    - sleep 60

script:
    - dotnet restore Com.DanLiris.Service.Sales.Test/Com.DanLiris.Service.Sales.Test.csproj
    - dotnet build Com.DanLiris.Service.Sales.Test/Com.DanLiris.Service.Sales.Test.csproj
    - dotnet test Com.DanLiris.Service.Sales.Test/Com.DanLiris.Service.Sales.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

after_success:
    - curl -s https://codecov.io/bash > codecov
    - chmod +x codecov
    - ./codecov -f "/home/travis/build/danliris/com-danliris-service.sales/Com.DanLiris.Service.Sales.Test/coverage.info"
      fi
